export enum EnumRegisterItemCode{
    REGISTER_OFF = 'REGISTER_OFF',
    REGISTER_OVERTIME = 'REGISTER_OVERTIME',
    EXPLAIN_WORK = 'EXPLAIN_WORK',
    REGISTER_HISTORY = 'REGISTER_HISTORY',
    PROFILE_STAFF = 'PROFILE_STAFF',
    PROFILE_INFO = 'PROFILE_INFO',
    WORK_IN_PAST = 'WORK_IN_PAST',
    WORK_IN_PRESENT = 'WORK_IN_PRESENT',
    FAMILY_INFO = 'FAMILY_INFO',
    CERTIFICATE = 'CERTIFICATE',
    CURRICULUM = 'CURRICULUM',
    EDUCATION = 'EDUCATION',
    INS_INFO = 'INS_INFO',
    BANK_INFO = 'BANK_INFO',
    CONTACT_INFO = 'CONTACT_INFO',
    ADDITINATIONAL_INFO = 'ADDITINATIONAL_INFO'
  
}