export class Position {
  id?: number;
  groupId?: number;
  code?: string;
  name?: string;
  note?: string;
  jobDesc?: string;
  tenantId?: number;
  isActive?: number;
  createBy?: string;
  updatedBy?: string;
  createDate?: Date;
  updatedDate?: Date;
  orgid?:number;
  orgname?:string;
  jobid?:number;
  jobname?:string;
  lm?:number;
  lmposition?:string;
  lmname?:string;
  isowner?:boolean;
  csm?:number;
  csmposition?:string;
  csmname?:string;
  isnonphysical?:boolean;
  master?:number;
  mastername?:string;
  concurrent?:number;
  isplan?:boolean;
  interim?:number;
  interimname?:string;
  effectivedate?: Date;
  typeactivities?: string;
  filename?: string;
  uploadfile?: string;
  workingtime?:number;
  nameEn?: string;
  chairId?: Array<number>;
  chair2Id?: Array<number>;
  textboxSearch?: string;
  textbox2Search?: string;
  orgIdSearch?:number;
  orgIdSearchText?:string;
  orgId2Search?:number;
  _positionDesc?: PositionDesc;
}
  export class PositionDesc {
    id?:number;
    jobtarget1?: string;
    jobtarget2?: string;
    jobtarget3?: string;
    jobtarget4?: string;
    jobtarget5?: string;
    jobtarget6?: string;
    tdcm?: number;
    major?: string;
    workexp?: string;
    language?: number;
    computer?: number;
    supportskill?: string;
    internal1?: string;
    internal2?: string;
    internal3?: string;
    outside1?: string;
    outside2?: string;
    outside3?: string;
    responsibility1?: string;
    responsibility2?: string;
    responsibility3?: string;
    responsibility4?: string;
    responsibility5?: string;
    detailresponsibility1?: string;
    detailresponsibility2?: string;
    detailresponsibility3?: string;
    detailresponsibility4?: string;
    detailresponsibility5?: string;
    outresult1?: string;
    outresult2?: string;
    outresult3?: string;
    outresult4?: string;
    outresult5?: string;
    permission1?: string;
    permission2?: string;
    permission3?: string;
    permission4?: string;
    permission5?: string;
    permission6?: string;
    filename?: string;
    positionid?: number;
  }
